generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ocSnapshot
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          oc_snapshot
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: {}
      fields:  ~
      list:
        title: Manage placements
        display: [id, name, day, created_at, sf_guard_user_id]
        batch_actions: {}
        object_actions: {}
        actions: {}
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
