<?php

/**
 * PluginOcSnapshotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcSnapshotTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcSnapshotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcSnapshot');
    }
    
    public function createQuery($alias = 'ocs') 
    {
      $user = sfContext::getInstance()->getUser()->getGuardUser();
      
      $q = parent::createQuery($alias)
        ->andWhere("$alias.group_id = ?", $user->OcConfig->group_id)
        ->andWhere("$alias.workspace_id = ?", $user->OcConfig->workspace_id);
        
      return $q;
    }
    
    public function getLast($day = null, $type = null)
    {
      $q = $this->createQuery('ocs');
      $root = $q->getRootAlias();
      
      $q->andWhere("$root.purpose = ?", $type)
        ->andWhere("$root.day = ?", $day)
        ->orderBy("$root.created_at DESC");
        
      return $q;
    }
    
    public function getLastValid($day = null) 
    {
      return $this->getLast($day, 'valid');
    }
    
    public function getLastInit($day = null) 
    {
      return $this->getLast($day, 'init');
    }
}