<?php

/**
 * PluginOcTimeSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginOcTimeSlot extends BaseOcTimeSlot
{
    public function postSave($event)
    {
        $this->OcTimeSlotManifestations->delete();
        
        $q = Doctrine::getTable('Manifestation')->createQuery('m', true)
            ->andWhere('m.happens_at >= ?', $this->starts_at)
            ->andWhere('m.happens_at <  ?', $this->ends_at);
        foreach ( $q->execute() as $manif ) {
            $tsm = new OcTimeSlotManifestation;
            $tsm->Manifestation = $manif;
            $tsm->OcTimeSlot = $this;
            $tsm->save();
        }
        
        parent::postSave($event);
    }
}
