<?php

/**
 * PluginOcProfessional
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginOcProfessional extends BaseOcProfessional
{
    public function preSave($event)
    {
        if ( !$this->rank ) {
            $max = Doctrine::getTable('OcProfessional')->createQuery('op')
                ->orderBy('op.rank DESC')
                ->select('op.rank')
                ->limit(1)
                ->fetchArray();
            $this->rank = $max['rank']+1;
        }
        
        parent::preSave($event);
    }
}
