<?php

/**
 * PluginOcSnapshotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcSnapshotTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcSnapshotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcSnapshot');
    }
    
    
    public function getLastValid($day = null) 
    {
      return parent::createQuery('ocs')
        ->andWhere('ocs.purpose = ?', 'valid')
        ->andWhere('ocs.day = ?', $day)
        ->orderBy('ocs.created_at DESC');
    }
}