<?php

/**
 * PluginOcTimeSlotManifestationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginOcTimeSlotManifestationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginOcTimeSlotManifestationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginOcTimeSlotManifestation');
    }
}