generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ocProfessional
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          oc_backend
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        li_oc
    
    config:
      actions: ~
      fields:  ~
      list:
        title: Liste des évènements
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
