default:
  javascripts: [/liOnlineChoicesPlugin/js/oc_backend, /liOnlineChoicesPlugin/js/jquery.multisortable.js]
  stylesheets: [/liOnlineChoicesPlugin/css/oc_backend]

jsonSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
listSnapshotsSuccess:
  has_layout: false