
#
# CUSTOMER
#
api_customers:
    url: /api/v2/customers
    class: sfRequestRoute
    param: { module: apiCustomers, action: index }
    requirements:
        sf_method: [GET, POST]

api_customers_resource:
    url: /api/v2/customers/:customer_id
    class: sfRequestRoute
    param: { module: apiCustomers, action: resource }
    requirements:
        customer_id: \d+
        sf_method: [GET, POST, DELETE]

#
# CUSTOMER ORDER
#
api_customers_orders:
    url: /api/v2/customers/:customer_id/orders
    class: sfRequestRoute
    param: { module: apiCustomerOrders, action: index }
    requirements:
        sf_method: [GET]
        
api_customers_orders_resource:
    url: /api/v2/customers/:customer_id/orders/:order_id
    class: sfRequestRoute
    param: { module: apiCustomerOrders, action: resource }
    requirements:
        customer_id: \d+
        order_id: \d+
        sf_method: [GET]


#
# MANIFESTATION 
#
api_manifestations:
    url: /api/v2/manifestations
    class: sfRequestRoute
    param: { module: apiManifestations, action: index }
    requirements:
        sf_method: [GET]

api_manifestations_resource:
    url: /api/v2/manifestations/:manifestation_id
    class: sfRequestRoute
    param: { module: apiManifestations, action: resource }
    requirements:
        manifestation_id: \d+
        sf_method: [GET]
        
#
# ORDERS 
#

api_orders:
    url: /api/v2/orders
    class: sfRequestRoute
    param: { module: apiOrders, action: index }
    requirements:
        sf_method: [GET]
        
api_orders_resource:
    url: /api/v2/orders/:order_id
    class: sfRequestRoute
    param: { module: apiOrders, action: resource }
    requirements:
        order_id: \d+
        sf_method: [GET]

api_orders_action:
    url: /api/v2/orders/:do_action/:order_id
    class: sfRequestRoute
    param: { module: apiOrders, action: action }
    requirements:
        order_id: \d+
        do_action: ship|cancel|complete
        sf_method: [GET]