# config/services.yml
dev:
  parameters:

all:
  parameters:
    
  services:
      actions_service:
          class: ApiActionsService
      translation_service:
          class: ApiTranslationService
      oauth_service:
          class: ApiOAuthService
      customers_service:
          class: ApiCustomersService
          calls:
            - ['setOAuthServiceService', ['@oauth_service']]
      events_service:
          class: ApiEventsService
          calls:
            - ['setManifestationsService', ['@manifestations_service']]
            - ['setTranslationService', ['@translation_service']]
      manifestations_service:
          class: ApiManifestationsService
          calls:
            - ['setTranslationService', ['@translation_service']]
      carts_service:
          class: ApiCartsService
      cartitems_service:
          class: ApiCartItemsService
          
