# config/services.yml
dev:
  parameters:

all:
  parameters:

  services:
      api_actions_service:
          class: ApiActionsService
      api_translation_service:
          class: ApiTranslationService
      api_oauth_service:
          class: ApiOAuthService
      api_customers_service:
          class: ApiCustomersService
          calls:
            - ['setOAuthService', ['@api_oauth_service']]
      api_events_service:
          class: ApiEventsService
          calls:
            - ['setApiManifestationsService', ['@api_manifestations_service']]
            - ['setTranslationService', ['@api_translation_service']]
            - ['setOAuthService', ['@api_oauth_service']]
      api_manifestations_service:
          class: ApiManifestationsService
          calls:
            - ['setTranslationService', ['@api_translation_service']]
            - ['setOAuthService', ['@api_oauth_service']]
            - ['setManifestationsService', ['@manifestations_service']] # from project
      api_cartitems_service:
          class: ApiCartItemsService
          calls:
            - ['setOAuthService', ['@api_oauth_service']]
      api_carts_service:
          class: ApiCartsService
          calls:
            - ['setOAuthService', ['@api_oauth_service']]
            - ['setCartItemsService', ['@api_cartitems_service']]
            - ['setCustomersService', ['@api_customers_service']]


