# config/services.yml
dev:
  parameters:

all:
  parameters:
    
  services:
      oauth_service:
          class: ApiOAuthService
      customers_service:
          class: ApiCustomersService
          arguments: ["@oauth_service"]
          
