generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OcApplication
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          oc_application
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        li_oc

    config:
      actions: ~
      fields:
        secret_new:
          label: Secret
          help: Let it empty if no change is required
      list:
        display: [identifier, _user]
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [identifier, user_id]
      form:
        display: [identifier, secret_new, _generator, user_id]
      edit:    ~
      new:     ~
