generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OcTimeSlot
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          oc_time_slot
    with_doctrine_route:   true
    actions_base_class:    sfActions
    i18n_catalogue:        li_oc

    config:
      actions: ~
      fields:
        starts_before:
          type: date
        ends_after:
          type: date
      list:
        display: [name, starts_at, ends_at]
        sort: [starts_at, asc]
        actions:
            _new: ~
            _refresh:
                label: Refresh Manifs
                action: refresh
                ui-icon: refresh
        object_actions:
          _edit: ~
          _delete: ~
      filter:
        display: [name, starts_before, ends_after]
      form:
        display: [name, starts_at, ends_at]
      edit: ~
      new: ~
