all:
  is_secure: true

index:
  credentials: [tck-onlinechoices-ts]
edit:
  credentials: [tck-onlinechoices-ts-edit]
del:
  credentials: [tck-onlinechoices-ts-del]
new:
  credentials: [tck-onlinechoices-ts-new]
