OcTicket:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    oc_transaction_id:
      type: integer
      notnull: true
    price_id:
      type: integer
      notnull: true
    gauge_id:
      type: integer
      notnull: true
    rank:
      type: integer
      notnull: true
      default: 1
    accepted:
      type: enum
      values: [none, human, algorithm]
      default: none
  relations:
    OcTransaction:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcTickets
    Price:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcTickets
    Gauge:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcTickets
OcTransaction:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    oc_professional_id: integer
    transaction_id: integer
    oc_token_id: integer
  relations:
    OcProfessional:
      onDelete: SET NULL
      onUpdate: CASCADE
      foreignAlias: OcTransactions
    Transaction:
      onDelete: SET NULL
      onUpdate: CASCADE
      foreignAlias: OcTransactions
    OcToken:
      onDelete: SET NULL
      onUpdate: SET NULL
      foreignAlias: OcTransaction
      type: one
OcProfessional:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    professional_id:
      type: integer
      notnull: true
    rank:
      type: integer
      default: 1
      notnull: true
  relations:
    Professional:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcProfessionals
OcConfig:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    sf_guard_user_id:
      type: integer
      notnull: true
      unique: true
    group_id:
      type: integer
      notnull: true
    workspace_id: integer
  relations:
    Workspace:
      onDelete: SET NULL
      onUpdate: CASCADE
      foreignAlias: OcConfigs
    sfGuardUser:
      foreignType: one
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcConfig
    Group:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcConfigs
OcTimeSlot:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    name:
      type: string(255)
      notnull: true
    starts_at:
      type: timestamp
      notnull: true
    ends_at:
      type: timestamp
      notnull: true
  relations:
    Manifestations:
      class: Manifestation
      refClass: OcTimeSlotManifestation
      foreignAlias: OcTimeSlots
OcTimeSlotManifestation:
  columns:
    manifestation_id:
      type: integer
      notnull: true
    oc_time_slot_id:
      type: integer
      notnull: true
  relations:
    Manifestation:
      foreignAlias: OcTimeSlotManifestations
      onDelete: CASCADE
      onUpdate: CASCADE
    OcTimeSlot:
      foreignAlias: OcTimeSlotManifestations
      onDelete: CASCADE
      onUpdate: CASCADE
    
OcToken:
  inheritance:
    extends: Traceable
    type: concrete
  columns:
    token:
      type: string(255)
      notnull: true
    refresh_token:
      type: string(255)
      notnull: true
    expires_at:
      type: timestamp
      notnull: true
    oc_application_id:
      type: integer
      notnull: true
  indexes:
    oc_token_token_idx:
      fields: [token]
  relations:
    OcApplication:
      onDelete: CASCADE
      onUpdate: CASCADE
      foreignAlias: OcTokens
OcApplication:
  inheritance:
    extends: Dummy
    type: concrete
  columns:
    identifier:
      type: string(255)
      notnull: true
    secret:
      type: string(255)
      notnull: true
    user_id:
      type: integer
      notnull: true
    expires_at: timestamp
  indexes:
    oc_application_identifier_secret_idx:
      fields: [identifier, secret]
  relations:
    User:
      local: user_id
      class: sfGuardUser
      foreignAlias: OcApplications
      onDelete: CASCADE
      onUpdate: CASCADE

OcSnapshot:
  actAs:
    Timestampable: ~
  columns:
    name: string(255)
    day: 
      type: timestamp
      notnull: true
    purpose:
      type: enum
      values: [temp, save, valid]
      default: temp
    content:
      type: string
      notnull: true
    sf_guard_user_id:
      type: integer
      notnull: true
  relations:
    sfGuardUser:
      foreignAlias: ocSnapshots

